### ISSUE TITLE
Installation of pygit2 is failing

### ISSUE THREAD

**Issue by johnsamuelwrites** [libgit2/pygit2#999]
On running 

`pip3 install  pygit2`

I get the following error on Ubuntu 19.10

```
src/types.h:36:2: error: #error You need a compatible libgit2 version (1.0.x)
       36 | #error You need a compatible libgit2 version (1.0.x)
          |  ^~~~~
    src/types.h:251:5: error: unknown type name ‘git_mailmap’
      251 |     git_mailmap *mailmap;
          |     ^~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

A previous [issue](https://github.com/libgit2/pygit2/issues/512) suggested installing `libgit2-dev `and also `build-essential libffi-dev python-dev libgit2-dev`, but there is no change. Am I missing any particular installation.

Following is the version of libgit installed.

```
$ ldconfig -p | grep libgit
	libgit2.so.27 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgit2.so.27
	libgit2.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libgit2.so

```

**Comment by m451** [comment]
You need to get the environment variable `LIBGIT2` and it has to point to the binaries of libgit2 version >= 1.0.0. From the error I suppose because you installed libgit2 using your OS repos that libgit2 version is <= 1.0.0. Pygit2 >= 1.2.0 requires libgit2 >= 1.0.0.

**Comment by jdavid** [comment]
Actually libgit2 is included in the binary Linux wheels, so don't need for this.

My guess is that you're trying to install latest pygit2 with Python 2, which doesn't work. Since the wheel is not available for Python 2 then it tries to build it, and fails because you have an old version of libgit2.

Your choices are:

- Use the packaged version, that's python3-pygit2 in Ubuntu 19.10
- Use the latest version of pygit2, which includes libgit2. That only works with Python 3.6 or later.

Most Linux users don't need to build pygit2 at all.

**Comment by jdavid** [comment]
Ok I see now you're using pip3. In any case it's not picking the binary wheel as it should. Maybe it's an old version of Python 3? Only Python 3.6 or later is supported. Or may it be a 32bit system? We only distribute Linux wheels for 64bit platforms.

**Comment by jdavid** [comment]
Alright, I could test in a Ubuntu 19.10 box. To fix it you need to upgrade pip. For example this works:

```
pip3 install -U pip
pip install pygit2
```

**Comment by johnsamuelwrites** [comment]
Hi @jdavid,

I am using Python 3.7.5
```
$ python3 --version
Python 3.7.5
```
and I am using pip3. 
I resolved the problem by compiling the source code (similar to the steps given by @m451) and the problem is resolved. 

I think, this is a problem that was discovered after the release of libgit2 v1.0.0.

**Comment by jdavid** [comment]
Ok, it doesn't work with pip 18.1, and it does with pip 19.0+

**Comment by jdavid** [comment]
Added a warning to the documentation. Thanks for reporting.

**Comment by ddkn** [comment]
To add to this, I was using pip 20.3.4 on OpenBSD 6.9 and it was required I `pkg_add libgit2` prior to `pip install pygit2` for pygit2 to install. This was a dependency for [dvc](https://dvc.org), `pip install dvc`. You may want to add this to the documentation that in some OS instances, one may need to install the libgit2 libraries.
