### ISSUE TITLE
pygit2 cant build in git1.8.0

### ISSUE THREAD

**Issue by wolftankk** [libgit2/pygit2#140]
Hi,
In git 1.8.0, pygit2 cant build. Error info:

src/pygit2/config.c: In function ‘Config_foreach’:
src/pygit2/config.c:261:13: warning: passing argument 2 of ‘git_config_foreach’ from incompatible pointer type [enabled by default]
In file included from /usr/include/git2.h:38:0,
                 from include/pygit2/error.h:33,
                 from src/pygit2/config.c:30:
/usr/include/git2/config.h:420:17: note: expected ‘int (_)(const struct git_config_entry *, void *)’ but argument is of type ‘int (_)(const char _, const char *, void *)’
src/pygit2/config.c: In function ‘Config_add_file’:
src/pygit2/config.c:276:5: error: too few arguments to function ‘git_config_add_file_ondisk’
In file included from /usr/include/git2.h:38:0,
                 from include/pygit2/error.h:33,
                 from src/pygit2/config.c:30:
/usr/include/git2/config.h:206:17: note: declared here
src/pygit2/config.c: In function ‘Config_get_multivar’:
src/pygit2/config.c:311:13: warning: passing argument 4 of ‘git_config_get_multivar’ from incompatible pointer type [enabled by default]
In file included from /usr/include/git2.h:38:0,
                 from include/pygit2/error.h:33,
                 from src/pygit2/config.c:30:
/usr/include/git2/config.h:339:17: note: expected ‘int (_)(const struct git_config_entry _, void *)’ but argument is of type ‘int (_)(const char *, void *)’
error: command 'gcc' failed with exit status 1
