### ISSUE TITLE
Linker fails when building on Windows

### ISSUE THREAD

**Issue by poke** [libgit2/pygit2#110]
Hey, I have been trying all day to get pygit2 running on my machine. I successfully built libgit2 (a few times by now, with different options) but I simply can’t get pygit2 working. I keep getting unresolved symbols when linking, and I can’t really figure out why.

Below you can see the link command being invoked and some of the error messages (I truncated them, as it was basically repeating the same over and over again just with a different symbol/object name):

```
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\libgit2\lib" "/LIBPATH:C:\Program Files\Python32\libs" "/LIBPATH:C:\Program Files\Python32\PCbuild\amd64" git2.lib /EXPORT:PyInit__pygit2 build\temp.win-amd64-3.2\Release\src\pygit2.obj build\temp.win-amd64-3.2\Release\src\pygit2\blob.obj build\temp.win-amd64-3.2\Release\src\pygit2\commit.obj build\temp.win-amd64-3.2\Release\src\pygit2\config.obj build\temp.win-amd64-3.2\Release\src\pygit2\diff.obj build\temp.win-amd64-3.2\Release\src\pygit2\error.obj build\temp.win-amd64-3.2\Release\src\pygit2\index.obj build\temp.win-amd64-3.2\Release\src\pygit2\object.obj build\temp.win-amd64-3.2\Release\src\pygit2\oid.obj build\temp.win-amd64-3.2\Release\src\pygit2\reference.obj build\temp.win-amd64-3.2\Release\src\pygit2\repository.obj build\temp.win-amd64-3.2\Release\src\pygit2\signature.obj build\temp.win-amd64-3.2\Release\src\pygit2\tag.obj build\temp.win-amd64-3.2\Release\src\pygit2\tree.obj build\temp.win-amd64-3.2\Release\src\pygit2\utils.obj build\temp.win-amd64-3.2\Release\src\pygit2\walker.obj /OUT:build\lib.win-amd64-3.2\_pygit2.pyd /IMPLIB:build\temp.win-amd64-3.2\Release\src\_pygit2.lib /MANIFESTFILE:build\temp.win-amd64-3.2\Release\src\_pygit2.pyd.manifest
pygit2.obj : warning LNK4197: export 'PyInit__pygit2' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.2\Release\src\_pygit2.lib and object build\temp.win-amd64-3.2\Release\src\_pygit2.exp
pygit2.obj : error LNK2019: unresolved external symbol git_repository_free referenced in function init_repository
repository.obj : error LNK2001: unresolved external symbol git_repository_free
pygit2.obj : error LNK2019: unresolved external symbol git_repository_init referenced in function init_repository
pygit2.obj : error LNK2019: unresolved external symbol git_repository_discover referenced in function discover_repository
commit.obj : error LNK2019: unresolved external symbol git_commit_message_encoding referenced in function Commit_get_message_encoding
commit.obj : error LNK2019: unresolved external symbol git_commit_message referenced in function Commit_get_message
commit.obj : error LNK2019: unresolved external symbol git_commit_time referenced in function Commit_get_commit_time

[…] (this goes on for another 150 lines)

build\lib.win-amd64-3.2\_pygit2.pyd : fatal error LNK1120: 131 unresolved externals
error: command '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\link.exe"' failed with exit status 1120
```

I’m using Visual Studio 10 (2010) to build on Windows 7 x64 with Python 3.2.2 (x64); libgit2 was built with the same configurations and works fine.

Do you have any idea why this happens and what I can do to complete the build?
